id: P000663
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 16:35:51.046749
source_metadata:
  id: bdr:W23746
  title: བཀའ་གདམས་ཀྱི་སྐྱེས་བུ་དམ་པ་རྣམས་ཀྱི་གསུང་བགྲོས་ཐོར་བུ་བ་རྣམས
  author: ''
  volumes:
    1eb872111a4641589056f46eafd6fac1:
      image_group_id: I3174
      title: ''
      volume_number: 1
      total_pages: 56
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
