id: P000663
initial_creation_type: ocr
source_metadata:
  id: bdr:W23746
  title: བཀའ་གདམས་ཀྱི་སྐྱེས་བུ་དམ་པ་རྣམས་ཀྱི་གསུང་བགྲོས་ཐོར་བུ་བ་རྣམས
  author: ''
  volumes:
    1eb872111a4641589056f46eafd6fac1:
      image_group_id: I3174
      title: ''
      volume_number: 1
      total_pages: 56
      base_file: v001.txt
